DROP TABLE IF EXISTS reviewers CASCADE;

CREATE TABLE reviewers (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
);