DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  upc VARCHAR(255) NOT NULL,
  ingredient VARCHAR(255) NOT NULL,
  wholesale_price DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  retail_price DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  height INTEGER NOT NULL DEFAULT 0,
  length INTEGER NOT NULL DEFAULT 0,
  width INTEGER NOT NULL DEFAULT 0,
  weight INTEGER NOT NULL DEFAULT 0,
  inventory_threshold INTEGER NOT NULL DEFAULT 0,
  stock_level INTEGER NOT NULL DEFAULT 0,
  kit_or_bundle INTEGER NOT NULL DEFAULT 0,
  vendor_id INTEGER REFERENCES vendors(id) ON DELETE CASCADE
);